import type { Reef } from "@/lib/types";

export const reefSeedData: Reef[] = [
  {
    slug: "great-barrier-reef",
    name: "Great Barrier Reef",
    description: "The largest coral reef system on Earth, stretching along Australia.",
    latitude: -18.2871,
    longitude: 147.6992,
    facts: [
      "Visible from space on clear days.",
      "Home to more than 1,500 fish species.",
      "Supports tourism, fishing, and coastal protection.",
    ],
    issues: ["Mass bleaching", "Warming seas", "Cyclones"],
    stats: {
      coralCover: 62,
      fishDiversity: 88,
      waterClarity: 75,
      heatStress: 78,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "belize-barrier-reef",
    name: "Belize Barrier Reef",
    description: "Caribbean reef with the famous Great Blue Hole nearby.",
    latitude: 17.5243,
    longitude: -88.2019,
    facts: ["Second largest barrier reef system in the world."],
    issues: ["Ocean acidification", "Tourism pressure", "Storm damage"],
    stats: {
      coralCover: 55,
      fishDiversity: 70,
      waterClarity: 72,
      heatStress: 64,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "red-sea-reef",
    name: "Red Sea Reef",
    description: "Warm-water reefs known for high coral heat tolerance.",
    latitude: 20.0,
    longitude: 38.0,
    facts: [
      "Some corals show unusual heat resilience.",
      "Clear waters and dramatic reef drop-offs.",
    ],
    issues: ["Coastal development", "Pollution", "Warming seas"],
    stats: {
      coralCover: 68,
      fishDiversity: 76,
      waterClarity: 84,
      heatStress: 60,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "maldives-reef",
    name: "Maldives Atolls",
    description: "Ring-shaped coral islands with crystal lagoons.",
    latitude: 3.2028,
    longitude: 73.2207,
    facts: ["Atolls formed from ancient volcanic islands.", "Crystal lagoons inside ring reefs."],
    issues: ["Sea level rise", "Bleaching"],
    stats: {
      coralCover: 58,
      fishDiversity: 74,
      waterClarity: 82,
      heatStress: 71,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "tubbataha-reefs",
    name: "Tubbataha Reefs",
    description: "Remote Philippine reef park, a UNESCO World Heritage site.",
    latitude: 8.9575,
    longitude: 119.9144,
    facts: ["One of the most protected reefs in Southeast Asia.", "Seasonal access keeps biodiversity strong."],
    issues: ["Illegal fishing", "Storm damage"],
    stats: {
      coralCover: 72,
      fishDiversity: 82,
      waterClarity: 80,
      heatStress: 58,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
    {
    slug: "amazon-reef",
    name: "Amazon Reef",
    description: "Extensive coral and sponge reef system off Brazil and French Guiana.",
    latitude: 2.0,
    longitude: -51.0,
    image: "/reefguard logo.png",
    facts: [
      "One of the largest reef systems in the Atlantic Ocean.",
      "Discovered relatively recently and spans hundreds of miles.",
    ],
    issues: ["Pollution", "Oil exploration", "Overfishing"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "apo-reef",
    name: "Apo Reef",
    description: "Large coral reef system in the Philippines’ Mindoro Strait.",
    latitude: 12.7,
    longitude: 120.2,
    image: "/reefguard logo.png",
    facts: [
      "One of the largest contiguous coral reef systems in the world.",
      "Important habitat for turtles and fish.",
    ],
    issues: ["Illegal fishing", "Climate stress"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "bunaken-reef",
    name: "Bunaken National Marine Park",
    description: "Coral reef area around Bunaken Island, Indonesia.",
    latitude: 1.6,
    longitude: 124.8,
    image: "/reefguard logo.png",
    facts: [
      "Part of a marine park with hundreds of coral types.",
      "Noted for very high marine biodiversity.",
    ],
    issues: ["Tourism pressure", "Pollution"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "bar-reef",
    name: "Bar Reef",
    description: "Coral reef near Kalpitiya, Sri Lanka.",
    latitude: 8.0,
    longitude: 79.8,
    image: "/reefguard logo.png",
    facts: [
      "One of the richest reef ecosystems in the Indian Ocean.",
      "Important site for conservation in Sri Lanka.",
    ],
    issues: ["Coastal development", "Fishing impacts"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "ningaloo-coast",
    name: "Ningaloo Reef",
    description: "Fringing coral reef along Western Australia.",
    latitude: -22.3,
    longitude: 113.8,
    image: "/reefguard logo.png",
    facts: [
      "UNESCO World Heritage site.",
      "Whale sharks frequent its waters seasonally.",
    ],
    issues: ["Marine heatwaves", "Tourism impacts"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "yabiji",
    name: "Yabiji Reefs",
    description: "Large reef group in the Miyako Islands, Japan.",
    latitude: 24.9,
    longitude: 125.3,
    image: "/reefguard logo.png",
    facts: [
      "Japan’s largest coral reef grouping.",
      "Contains hundreds of individual reef patches.",
    ],
    issues: ["Climate stress", "Fishing pressure"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "mesoamerican-reef",
    name: "Mesoamerican Barrier Reef",
    description: "Extensive reef system along the Caribbean coasts of Mexico, Belize, Guatemala, and Honduras.",
    latitude: 18.5,
    longitude: -87.5,
    image: "/reefguard logo.png",
    facts: [
      "Second-largest barrier reef system in the world.",
      "Supports fisheries and tourism across four countries.",
    ],
    issues: ["Pollution", "Sargassum inundations", "Climate change"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "miami-terrace-reef",
    name: "Miami Terrace Reef",
    description: "Deep‑water coral reef off Florida, United States.",
    latitude: 25.0,
    longitude: -80.5,
    image: "/reefguard logo.png",
    facts: [
      "Deep‑sea reef with unique coral species.",
      "Less exposed to surface temperature variations.",
    ],
    issues: ["Fishing gear damage", "Acidification"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "rost-reef",
    name: "Røst Reef",
    description: "Deep‑water coral reef off the coast of Norway.",
    latitude: 67.5,
    longitude: 11.0,
    image: "/reefguard logo.png",
    facts: [
      "World’s largest known Lophelia deep coral reef.",
      "Important habitat for cold‑water species.",
    ],
    issues: ["Trawling", "Pollution"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  
  {
    slug: "raja-ampat",
    name: "Raja Ampat",
    description: "Indonesian reef hotspot with incredible biodiversity.",
    latitude: -0.2333,
    longitude: 130.5167,
    facts: ["Part of the Coral Triangle biodiversity zone.", "Hundreds of coral species in one region."],
    issues: ["Overfishing", "Plastic waste", "Rising temperatures"],
    stats: {
      coralCover: 76,
      fishDiversity: 92,
      waterClarity: 78,
      heatStress: 66,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "palau-reef",
    name: "Palau Reef",
    description: "Micronesian reefs famous for jellyfish lake nearby.",
    latitude: 7.51498,
    longitude: 134.5825,
    facts: ["Palau created one of the world’s first shark sanctuaries.", "Jellyfish Lake nearby is famous worldwide."],
    issues: ["Tourism pressure", "Warming seas"],
    stats: {
      coralCover: 70,
      fishDiversity: 80,
      waterClarity: 86,
      heatStress: 59,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "hawaiian-reef",
    name: "Hawaiian Reefs",
    description: "Volcanic island reefs with unique endemic species.",
    latitude: 19.8968,
    longitude: -155.5828,
    facts: ["Many reef fish are found nowhere else.", "Volcanic islands shape reef habitats."],
    issues: ["Runoff pollution", "Bleaching", "Invasive algae"],
    stats: {
      coralCover: 52,
      fishDiversity: 68,
      waterClarity: 70,
      heatStress: 73,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "florida-keys-reef",
    name: "Florida Keys Reef",
    description: "Only barrier reef system in the continental U.S.",
    latitude: 24.5551,
    longitude: -81.7800,
    facts: ["Reefs support tourism and fisheries in Florida.", "Only barrier reef in the continental U.S."],
    issues: ["Coral disease", "Hurricanes", "Water quality"],
    stats: {
      coralCover: 48,
      fishDiversity: 62,
      waterClarity: 66,
      heatStress: 79,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "galapagos-reef",
    name: "Galapagos Reefs",
    description: "Equatorial reefs influenced by cold currents.",
    latitude: -0.9538,
    longitude: -90.9656,
    facts: ["Unique mix of tropical and temperate species.", "Cold currents fuel high productivity."],
    issues: ["El Nino warming events", "Invasive species", "Illegal fishing"],
    stats: {
      coralCover: 60,
      fishDiversity: 74,
      waterClarity: 78,
      heatStress: 69,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "andros-barrier-reef",
    name: "Andros Barrier Reef",
    description: "Massive reef system in the Bahamas.",
    latitude: 24.7,
    longitude: -77.7,
    facts: ["Second longest barrier reef in the world.", "Blue holes connect to deep ocean caves."],
    issues: ["Overfishing", "Storm damage", "Coastal runoff"],
    stats: {
      coralCover: 57,
      fishDiversity: 66,
      waterClarity: 74,
      heatStress: 65,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "spermonde-reefs",
    name: "Spermonde Reefs",
    description: "Island chain reefs off South Sulawesi.",
    latitude: -5.0,
    longitude: 119.5,
    facts: ["Reefs support local island fishing communities.", "Hundreds of small islands form a reef maze."],
    issues: ["Blast fishing", "Sedimentation", "Plastic waste"],
    stats: {
      coralCover: 50,
      fishDiversity: 63,
      waterClarity: 60,
      heatStress: 72,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "new-caledonia-reef",
    name: "New Caledonia Lagoon",
    description: "One of the largest lagoon reef systems on Earth.",
    latitude: -20.9,
    longitude: 165.6,
    facts: ["UNESCO-listed lagoon with massive biodiversity."],
    issues: ["Mining runoff", "Cyclones"],
    stats: {
      coralCover: 71,
      fishDiversity: 79,
      waterClarity: 80,
      heatStress: 63,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "society-islands-reef",
    name: "Society Islands Reefs",
    description: "French Polynesia reefs around Bora Bora and Moorea.",
    latitude: -17.65,
    longitude: -149.5,
    facts: ["Shallow lagoons with vibrant coral gardens."],
    issues: ["Warming seas", "Tourism pressure"],
    stats: {
      coralCover: 64,
      fishDiversity: 72,
      waterClarity: 83,
      heatStress: 67,
    },
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
];
