import type { Reef } from "@/lib/types";

export const reefSeedData: Reef[] = [
  {
    slug: "great-barrier-reef",
    name: "Great Barrier Reef",
    description: "The largest coral reef system on Earth, stretching along Australia.",
    latitude: -18.2871,
    longitude: 147.6992,
    image: "/reefguard logo.png",
    facts: [
      "Visible from space on clear days.",
      "Home to over 1,500 fish species.",
    ],
    issues: ["Mass bleaching", "Warming seas", "Cyclones"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "belize-barrier-reef",
    name: "Belize Barrier Reef",
    description: "Caribbean reef with the famous Great Blue Hole nearby.",
    latitude: 17.5243,
    longitude: -88.2019,
    image: "/reefguard logo.png",
    facts: ["Second largest barrier reef system in the world."],
    issues: ["Ocean acidification", "Tourism pressure"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "red-sea-reef",
    name: "Red Sea Reef",
    description: "Warm-water reefs known for high coral heat tolerance.",
    latitude: 20.0,
    longitude: 38.0,
    image: "/reefguard logo.png",
    facts: ["Some corals show unusual heat resilience."],
    issues: ["Coastal development", "Pollution"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "maldives-reef",
    name: "Maldives Atolls",
    description: "Ring-shaped coral islands with crystal lagoons.",
    latitude: 3.2028,
    longitude: 73.2207,
    image: "/reefguard logo.png",
    facts: ["Atolls formed from ancient volcanic islands."],
    issues: ["Sea level rise", "Bleaching"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "tubbataha-reefs",
    name: "Tubbataha Reefs",
    description: "Remote Philippine reef park, a UNESCO World Heritage site.",
    latitude: 8.9575,
    longitude: 119.9144,
    image: "/reefguard logo.png",
    facts: ["One of the most protected reefs in Southeast Asia."],
    issues: ["Illegal fishing", "Storm damage"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "raja-ampat",
    name: "Raja Ampat",
    description: "Indonesian reef hotspot with incredible biodiversity.",
    latitude: -0.2333,
    longitude: 130.5167,
    image: "/reefguard logo.png",
    facts: ["Part of the Coral Triangle biodiversity zone."],
    issues: ["Overfishing", "Plastic waste"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "palau-reef",
    name: "Palau Reef",
    description: "Micronesian reefs famous for jellyfish lake nearby.",
    latitude: 7.51498,
    longitude: 134.5825,
    image: "/reefguard logo.png",
    facts: ["Palau created one of the world’s first shark sanctuaries."],
    issues: ["Tourism pressure", "Warming seas"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "hawaiian-reef",
    name: "Hawaiian Reefs",
    description: "Volcanic island reefs with unique endemic species.",
    latitude: 19.8968,
    longitude: -155.5828,
    image: "/reefguard logo.png",
    facts: ["Many reef fish are found nowhere else."],
    issues: ["Runoff pollution", "Bleaching"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "florida-keys-reef",
    name: "Florida Keys Reef",
    description: "Only barrier reef system in the continental U.S.",
    latitude: 24.5551,
    longitude: -81.7800,
    image: "/reefguard logo.png",
    facts: ["Reefs support tourism and fisheries in Florida."],
    issues: ["Coral disease", "Hurricanes", "Water quality"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "galapagos-reef",
    name: "Galapagos Reefs",
    description: "Equatorial reefs influenced by cold currents.",
    latitude: -0.9538,
    longitude: -90.9656,
    image: "/reefguard logo.png",
    facts: ["Unique mix of tropical and temperate species."],
    issues: ["El Nino warming events", "Invasive species"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "andros-barrier-reef",
    name: "Andros Barrier Reef",
    description: "Massive reef system in the Bahamas.",
    latitude: 24.7,
    longitude: -77.7,
    image: "/reefguard logo.png",
    facts: ["Second longest barrier reef in the world."],
    issues: ["Overfishing", "Storm damage"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
  {
    slug: "mekong-reef",
    name: "Spermonde Reefs",
    description: "Island chain reefs off South Sulawesi.",
    latitude: -5.0,
    longitude: 119.5,
    image: "/reefguard logo.png",
    facts: ["Reefs support local island fishing communities."],
    issues: ["Blast fishing", "Sedimentation"],
    likes: 0,
    bookmarks: 0,
    reviews: [],
  },
];
